/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auctions/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get auctions list */
        post: operations["postAuctionsList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get auction details */
        get: operations["getAuctionByUuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionUuid}/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get auction bets history */
        get: operations["getAuctionBets"];
        put?: never;
        /** Set or update current carrier bet */
        post: operations["postAuctionBet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuctionsListRequest: {
            /** @default 1 */
            page: number;
            /** @default 10 */
            per_page: number;
            filters?: components["schemas"]["AuctionsListFilters"];
            sort?: components["schemas"]["AuctionsListSort"];
        };
        AuctionsListFilters: {
            /** @description Cargo request number substring. */
            cargo_num?: string | null;
            /**
             * @deprecated
             * @description Single status filter. Prefer `statuses`.
             */
            status?: components["schemas"]["AuctionStatus"] | null;
            statuses?: components["schemas"]["AuctionStatus"][] | null;
            auc_type?: components["schemas"]["AuctionType"] | null;
            /** Format: uuid */
            load_city_uuid?: string | null;
            /** Format: uuid */
            unload_city_uuid?: string | null;
            /** Format: date */
            loading_date_from?: string | null;
            /** Format: date */
            loading_date_to?: string | null;
            /** @description Only auctions where current user can set a bet. */
            is_available?: boolean | null;
            /** @description Only auctions where current user already has a bet. */
            is_bidder?: boolean | null;
            /** Format: double */
            price_from?: number | null;
            /** Format: double */
            price_to?: number | null;
        } | null;
        AuctionsListSort: {
            /** @enum {string} */
            field: "created_at" | "loading_date" | "current_price" | "cargo_num";
            direction: components["schemas"]["SortDirection"];
        } | null;
        AuctionsListResponse: {
            items: components["schemas"]["AuctionListItem"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        AuctionListItem: {
            /** Format: uuid */
            auction_uuid: string;
            /** @example UL-2026-000148 */
            cargo_num: string;
            auc_type: components["schemas"]["AuctionType"];
            status: components["schemas"]["AuctionStatus"];
            user_trading_status: components["schemas"]["UserTradingStatus"];
            route: components["schemas"]["RouteSummary"];
            /** Format: date */
            loading_date: string;
            /** Format: date */
            unloading_date: string | null;
            cargo: components["schemas"]["CargoSummary"];
            price: components["schemas"]["AuctionPriceSummary"];
            trading: components["schemas"]["AuctionTradingSummary"];
            has_my_bet: boolean;
            /** Format: date-time */
            created_at: string;
        };
        AuctionDetail: {
            /** Format: uuid */
            auction_uuid: string;
            cargo_num: string;
            auc_type: components["schemas"]["AuctionType"];
            status: components["schemas"]["AuctionStatus"];
            user_trading_status: components["schemas"]["UserTradingStatus"];
            organizer: components["schemas"]["Organizer"];
            contacts: components["schemas"]["AuctionContacts"];
            route: components["schemas"]["RouteDetail"];
            cargo: components["schemas"]["CargoDetail"];
            vehicle_requirements: components["schemas"]["VehicleRequirements"];
            payment: components["schemas"]["PaymentTerms"];
            price: components["schemas"]["AuctionPriceDetail"];
            trading: components["schemas"]["AuctionTradingDetail"];
            my_bet: components["schemas"]["MyBet"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuctionBetsResponse: {
            /** Format: uuid */
            auction_uuid: string;
            /** @description If true, bets history must not be shown to the user. */
            is_hidden: boolean;
            participants_count: number;
            items: components["schemas"]["Bet"][];
        };
        SetBetRequest: {
            /**
             * Format: double
             * @description Bet price with VAT in auction currency.
             */
            price: number;
            comment?: string | null;
        };
        SetBetResponse: {
            auction: components["schemas"]["AuctionDetail"];
            bet: components["schemas"]["Bet"];
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            total: number;
            pages: number;
        };
        RouteSummary: {
            load_city: components["schemas"]["City"];
            unload_city: components["schemas"]["City"];
            /** Format: double */
            distance_km: number | null;
        };
        RouteDetail: {
            points: components["schemas"]["RoutePoint"][];
            /** Format: double */
            distance_km: number | null;
        };
        RoutePoint: {
            /** Format: uuid */
            point_uuid: string;
            type: components["schemas"]["RoutePointType"];
            sequence: number;
            city: components["schemas"]["City"];
            /** @description Null when `hide_points_address_and_contacts` is true. */
            address: string | null;
            /** Format: date-time */
            date_from: string;
            /** Format: date-time */
            date_to: string | null;
            /** @description Empty when `hide_points_address_and_contacts` is true. */
            contacts: components["schemas"]["Contact"][];
        };
        City: {
            /** Format: uuid */
            uuid: string;
            name: string;
            region: string | null;
        };
        CargoSummary: {
            name: string;
            /** Format: double */
            weight_tons: number | null;
            /** Format: double */
            volume_m3: number | null;
            body_type: components["schemas"]["BodyType"];
        };
        CargoDetail: components["schemas"]["CargoSummary"] & {
            /** Format: uuid */
            cargo_uuid: string;
            packaging: string | null;
            places_count: number | null;
            /** Format: double */
            temperature_from: number | null;
            /** Format: double */
            temperature_to: number | null;
            is_hazardous: boolean;
        };
        VehicleRequirements: {
            body_type: components["schemas"]["BodyType"];
            /** @example side */
            loading_type: string | null;
            vehicle_count: number;
            extra_requirements: string[];
        };
        PaymentTerms: {
            /** @enum {string} */
            type: "Prepayment" | "OnUnload" | "Deferred";
            delay_days: number | null;
            note: string | null;
        };
        AuctionPriceSummary: {
            currency: components["schemas"]["Currency"];
            /**
             * Format: double
             * @description Null when `no_view_cargo_price` is true.
             */
            current_price: number | null;
            /** Format: double */
            price_per_km: number | null;
            /** Format: double */
            bet_step: number | null;
        };
        AuctionPriceDetail: components["schemas"]["AuctionPriceSummary"] & {
            /**
             * Format: double
             * @description Recommended next valid bet price.
             */
            available_price: number | null;
            /** Format: double */
            min_bet_price: number | null;
            /** Format: double */
            max_bet_price: number | null;
            /** Format: double */
            start_price: number | null;
            with_vat: boolean;
        };
        AuctionTradingSummary: {
            can_set_bet: boolean;
            hide_bets_history: boolean;
            hide_points_address_and_contacts: boolean;
            no_view_cargo_price: boolean;
        };
        AuctionTradingDetail: components["schemas"]["AuctionTradingSummary"] & {
            /** Format: date-time */
            starts_at: string | null;
            /** Format: date-time */
            ends_at: string | null;
            /** Format: date-time */
            server_time: string;
        };
        Organizer: {
            /** Format: uuid */
            uuid: string;
            name: string;
            inn: string | null;
        };
        AuctionContacts: {
            is_hidden: boolean;
            items: components["schemas"]["Contact"][];
        };
        Contact: {
            name: string | null;
            phone: string | null;
            /** Format: email */
            email: string | null;
        };
        MyBet: {
            /** Format: uuid */
            bet_uuid: string;
            /** Format: double */
            price: number;
            /** Format: double */
            price_without_vat: number | null;
            status: components["schemas"]["BetStatus"];
            ranking_place: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string | null;
        } | null;
        Bet: {
            /** Format: uuid */
            bet_uuid: string;
            carrier: components["schemas"]["Carrier"];
            /** Format: double */
            price: number;
            /** Format: double */
            price_without_vat: number | null;
            status: components["schemas"]["BetStatus"];
            ranking_place: number | null;
            is_winner: boolean;
            is_canceled: boolean;
            cancel_reason: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Carrier: {
            /** Format: uuid */
            uuid: string;
            name: string;
            is_current_user: boolean;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        ValidationErrorResponse: components["schemas"]["ErrorResponse"] & {
            errors: components["schemas"]["ValidationErrorItem"][];
        };
        ValidationErrorItem: {
            /** @example filters.price_from */
            field: string;
            message: string;
        };
        /** @enum {string} */
        AuctionType: "Request" | "Up" | "Down" | "FixPrice";
        /** @enum {string} */
        AuctionStatus: "Draft" | "Published" | "Trading" | "Finished" | "Canceled" | "Archived";
        /** @enum {string|null} */
        UserTradingStatus: "NotParticipant" | "Leading" | "Losing" | "Winner" | "Lost" | "Canceled" | null;
        /** @enum {string} */
        BetStatus: "Active" | "Outbid" | "Winner" | "Canceled" | "Rejected";
        /** @enum {string} */
        RoutePointType: "Load" | "Unload";
        /** @enum {string} */
        BodyType: "Tent" | "Refrigerator" | "Isothermal" | "Container" | "Flatbed" | "Any";
        /** @enum {string} */
        Currency: "RUB";
        /** @enum {string} */
        SortDirection: "asc" | "desc";
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Action is not available for the current user. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BET_FORBIDDEN",
                 *       "message": "Bet cannot be set for this auction."
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Auction was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AUCTION_NOT_FOUND",
                 *       "message": "Auction was not found."
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Auction state changed and request cannot be applied. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AUCTION_STATE_CHANGED",
                 *       "message": "Auction is no longer accepting bets."
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation error. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_ERROR",
                 *       "message": "Request validation failed.",
                 *       "errors": [
                 *         {
                 *           "field": "price",
                 *           "message": "Price must match auction step."
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
    };
    parameters: {
        /** @example 6bf9f6e6-c37f-4309-a132-f40ec1a79f09 */
        AuctionUuid: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postAuctionsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionsListRequest"];
            };
        };
        responses: {
            /** @description Auctions list with pagination metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionsListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAuctionByUuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 6bf9f6e6-c37f-4309-a132-f40ec1a79f09 */
                auctionUuid: components["parameters"]["AuctionUuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auction detail DTO. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAuctionBets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 6bf9f6e6-c37f-4309-a132-f40ec1a79f09 */
                auctionUuid: components["parameters"]["AuctionUuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bets history. If history is hidden, `is_hidden` is true and `items` is empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionBetsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    postAuctionBet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 6bf9f6e6-c37f-4309-a132-f40ec1a79f09 */
                auctionUuid: components["parameters"]["AuctionUuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBetRequest"];
            };
        };
        responses: {
            /** @description Bet was accepted and auction state was recalculated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetBetResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
}
